### ISSUE TITLE
Unable to install template from .middleman dir, use USER/REPO path instead?

### ISSUE THREAD

**Issue by timup** [elfacht/middleman-haml-boilerplate#9]
Installed the template in `~/.middleman`, but was unable to find the template when calling `middleman init`.

`Template `middleman-haml-boilerplate` not found in Middleman Directory.
Did you mean to use a full `user/repo` path?`

Install went fine using `middleman init PROJECT --template=USER/REPO`

Curious if others have run into this...

**Comment by elfacht** [comment]
The template name must be the same as the repo name. So when you checked out the repo as is and didn't change the repo name, it should be `middleman init my_project --template=middleman-haml-boilerplate`.

What does the error say exactly?

**Comment by timup** [comment]
``` zsh
$ middleman init my_project --template=middleman-haml-boilerplate 
Template `middleman-haml-boilerplate` not found in Middleman Directory.
Did you mean to use a full `user/repo` path?
```

Seems like a middleman v4 issue, as written up here:
https://github.com/middleman/middleman/issues/1777

And in the docs, here:
https://github.com/middleman/middleman-guides/commit/173657e1bc2f1b3362516518dfeeb4b67133b102

**Comment by elfacht** [comment]
Ok, thanks! Is it solved now?
